import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Termos de Uso — AcheiNoVale",
  description: "Termos que regulam o uso da plataforma AcheiNoVale.",
};

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Informações legais" title="Termos de Uso" description="Estas regras explicam como o AcheiNoVale funciona e quais são as responsabilidades de quem usa, anuncia ou presta serviços pela plataforma.">
      <section><h2>1. Aceitação dos Termos</h2><p>Ao acessar o AcheiNoVale, criar uma conta, publicar um anúncio ou usar qualquer funcionalidade, você declara que leu e concorda com estes Termos e com a Política de Privacidade. Se não concordar, não utilize a plataforma.</p></section>
      <section><h2>2. O que é o AcheiNoVale</h2><p>O AcheiNoVale é uma plataforma local que aproxima pessoas interessadas em imóveis e serviços de frete na região do Alto Vale do Itajaí. A plataforma organiza anúncios e facilita o contato entre usuários, inclusive por serviços externos como o WhatsApp.</p><p>O AcheiNoVale atua como intermediador de informações. Não é proprietário, imobiliária, corretor, transportador, empregador ou representante dos anunciantes e não participa dos pagamentos, contratos ou negociações realizadas entre usuários.</p></section>
      <section><h2>3. Cadastro e segurança da conta</h2><p>Algumas funções exigem uma conta. Você deve informar dados verdadeiros, completos e atualizados, proteger seu acesso e avisar o AcheiNoVale caso suspeite de uso indevido.</p><p>Não é permitido criar conta com identidade falsa, usar dados de terceiros sem autorização, compartilhar ou vender contas, tentar acessar áreas restritas ou utilizar a plataforma para fraude ou outra finalidade ilegal.</p></section>
      <section><h2>4. Publicação de anúncios</h2><p>Quem publica declara ter legitimidade e autorização para divulgar o imóvel, o serviço, as imagens, os vídeos e os dados apresentados. O anunciante é o único responsável pela veracidade, atualização e legalidade do preço, localização, disponibilidade, características, descrição e formas de contato.</p><p>Não publique o endereço exato de residências, documentos pessoais ou qualquer dado que não seja necessário para o anúncio. O AcheiNoVale poderá definir limites de mídia, campos obrigatórios e padrões de qualidade e segurança.</p></section>
      <section><h2>5. Moderação</h2><p>Anúncios podem ser analisados antes ou depois de ficarem públicos. O AcheiNoVale poderá aprovar, rejeitar, solicitar ajustes, ocultar ou remover conteúdos e suspender contas quando houver indícios de fraude, risco à comunidade, informação enganosa, violação destes Termos ou descumprimento da lei.</p><p>A aprovação de um anúncio não é certificação de identidade, propriedade, qualidade, procedência ou segurança da oferta.</p></section>
      <section><h2>6. Conteúdo proibido</h2><p>É proibido publicar conteúdo falso, discriminatório, ofensivo, ilegal, fraudulento, que viole direitos de terceiros, use mídia sem autorização, contenha código malicioso, promova spam ou tente obter dados e pagamentos de forma indevida.</p></section>
      <section><h2>7. Imóveis</h2><p>Antes de pagar, visitar ou assumir um compromisso, o interessado deve confirmar a identidade e a legitimidade do anunciante, verificar pessoalmente o imóvel quando possível e conferir documentos e condições da oferta. Não faça depósitos antecipados sem verificações suficientes.</p></section>
      <section><h2>8. Freteiros e prestadores</h2><p>Freteiros atuam de forma independente. Preço, prazo, pagamento, seguro, condições do veículo, execução e responsabilidade pelo transporte devem ser combinados diretamente entre cliente e prestador. O AcheiNoVale não contrata, supervisiona ou garante os serviços anunciados.</p></section>
      <section><h2>9. WhatsApp e serviços de terceiros</h2><p>Ao abrir links para WhatsApp, Google ou outros serviços, você também fica sujeito aos termos e políticas dessas empresas. O AcheiNoVale não controla mensagens, negociações, contratos ou pagamentos realizados fora da plataforma.</p></section>
      <section><h2>10. Negociações e prevenção a golpes</h2><p>As negociações são feitas diretamente entre os usuários. O AcheiNoVale não garante a conclusão do negócio, o pagamento, o cumprimento de promessas, a disponibilidade da oferta ou a identidade absoluta de cada pessoa.</p><p>Desconfie de preços muito abaixo do mercado, confirme identidades e documentos, não compartilhe senhas ou códigos de autenticação e denuncie anúncios suspeitos. Nada nestes Termos afasta responsabilidades que a lei atribua obrigatoriamente ao AcheiNoVale.</p></section>
      <section><h2>11. Direitos sobre o conteúdo</h2><p>Você mantém os direitos sobre os materiais que publica e declara possuir todas as autorizações necessárias. Ao enviar conteúdo, concede ao AcheiNoVale licença gratuita, não exclusiva e limitada para armazenar, adaptar tecnicamente, exibir e divulgar o anúncio enquanto ele estiver ativo ou pelo tempo necessário à operação e defesa de direitos.</p><p>A marca, identidade visual, código e materiais próprios do AcheiNoVale são protegidos e não podem ser copiados ou explorados sem autorização.</p></section>
      <section><h2>12. Disponibilidade e alterações</h2><p>A plataforma pode ficar indisponível por manutenção, falhas técnicas, fornecedores externos ou situações fora do controle razoável do AcheiNoVale. Funcionalidades podem ser corrigidas, alteradas ou encerradas para melhorar o serviço, a segurança ou atender à legislação.</p></section>
      <section><h2>13. Suspensão, encerramento e exclusão</h2><p>Contas e anúncios podem ser suspensos ou removidos em caso de violação destes Termos, fraude, abuso, risco a usuários ou ordem de autoridade competente. O usuário pode solicitar a exclusão da conta; certos registros poderão ser preservados para cumprir obrigações legais, prevenir fraude e exercer direitos.</p></section>
      <section><h2>14. Privacidade</h2><p>O tratamento de dados pessoais está explicado na Política de Privacidade, que integra estes Termos.</p></section>
      <section><h2>15. Atualizações destes Termos</h2><p>Estes Termos podem ser atualizados para refletir mudanças na plataforma ou na legislação. A versão vigente e a data da última atualização permanecerão publicadas nesta página. Mudanças relevantes poderão ser comunicadas por outros meios disponíveis.</p></section>
      <section><h2>16. Lei aplicável e contato</h2><p>Estes Termos são regidos pelas leis brasileiras, inclusive as normas de proteção do consumidor quando aplicáveis. O AcheiNoVale é um projeto operado por Paulo Cesar Dolzan, em Rio do Sul, Santa Catarina. Dúvidas, denúncias e solicitações podem ser enviadas para <a href="mailto:contato@acheinovale.com.br">contato@acheinovale.com.br</a>.</p></section>
    </LegalPage>
  );
}
