import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Política de Privacidade — AcheiNoVale",
  description: "Saiba como o AcheiNoVale coleta, utiliza e protege dados pessoais.",
};

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Seus dados" title="Política de Privacidade" description="Aqui você encontra, em linguagem direta, quais dados o AcheiNoVale utiliza, por que eles são necessários e como exercer seus direitos.">
      <section><h2>1. Quem trata seus dados</h2><p>O controlador dos dados descritos nesta Política é o AcheiNoVale, projeto operado por Paulo Cesar Dolzan, em Rio do Sul, Santa Catarina. Para assuntos de privacidade, entre em contato pelo e-mail <a href="mailto:contato@acheinovale.com.br">contato@acheinovale.com.br</a>.</p></section>
      <section><h2>2. Dados que podemos coletar</h2><h3>Cadastro e autenticação</h3><p>Nome, e-mail, foto de perfil, identificadores da conta e informações autorizadas quando você entra com o Google.</p><h3>Perfil e contato</h3><p>Cidade, telefone, número de WhatsApp, foto e outras informações que você decide incluir no perfil.</p><h3>Anúncios de imóveis</h3><p>Título, descrição, finalidade, tipo, preço, cidade, bairro, características, fotos, vídeos, CEP, rua, número, complemento e contato do anunciante. O endereço detalhado é armazenado como dado privado para administração e segurança do anúncio; publicamente mostramos apenas cidade e bairro.</p><h3>Perfis de freteiros</h3><p>Nome profissional, descrição, WhatsApp, cidade, raio de atendimento, serviços, disponibilidade e informações relacionadas ao veículo ou ao trabalho.</p><h3>Uso e segurança</h3><p>Endereço IP, navegador, dispositivo, sistema operacional, data e horário, páginas acessadas, pesquisas, cliques, registros de erro e eventos de segurança.</p></section>
      <section><h2>3. Para que usamos os dados</h2><p>Usamos dados para criar e autenticar contas; completar perfis; publicar, exibir e administrar anúncios; permitir contato por WhatsApp; oferecer pesquisa e filtros; moderar conteúdo; prevenir fraude e abuso; investigar denúncias; proteger usuários; corrigir falhas; medir desempenho; melhorar a plataforma; cumprir obrigações legais; atender solicitações de privacidade e exercer direitos.</p></section>
      <section><h2>4. Bases legais</h2><p>Conforme a finalidade, o tratamento pode ocorrer para executar o serviço solicitado e os Termos de Uso, cumprir obrigação legal, exercer direitos, proteger o crédito, atender a interesses legítimos do AcheiNoVale ou de terceiros com respeito aos direitos do titular, e mediante consentimento quando essa for a base adequada.</p><p>Quando o tratamento depender de consentimento, você poderá revogá-lo, sem afetar atos realizados anteriormente.</p></section>
      <section><h2>5. Informações que ficam públicas</h2><p>Por ser uma plataforma de anúncios, fotos, vídeos, descrição, preço, cidade, bairro, características do imóvel ou serviço, nome profissional e WhatsApp escolhido para contato podem ficar públicos. Não publique endereço residencial exato, documentos ou informações desnecessárias.</p></section>
      <section><h2>6. Com quem compartilhamos</h2><p>O AcheiNoVale não vende dados pessoais. Podemos compartilhar apenas o necessário com fornecedores de infraestrutura e operação, como Vercel para hospedagem e métricas, Supabase para autenticação, banco de dados e armazenamento, Google para login e WhatsApp quando você decide iniciar um contato. Ao buscar um endereço, o CEP informado é consultado no serviço ViaCEP; a lista oficial de municípios utiliza dados do IBGE.</p><p>Dados também podem ser fornecidos para cumprir ordem judicial, solicitação válida de autoridade, obrigação legal, prevenir fraude ou exercer e defender direitos. Cada serviço externo possui seus próprios termos e políticas.</p></section>
      <section><h2>7. Cookies e tecnologias semelhantes</h2><p>Podemos usar cookies e armazenamento local necessários para autenticação, segurança, preferências e funcionamento da plataforma. Também utilizamos métricas para entender desempenho e uso do site. Quando a legislação exigir consentimento para uma tecnologia não essencial, disponibilizaremos uma escolha adequada.</p></section>
      <section><h2>8. Armazenamento, segurança e transferências</h2><p>Adotamos medidas técnicas e administrativas razoáveis para reduzir riscos de acesso indevido, perda, alteração ou divulgação não autorizada. Nenhum sistema conectado à internet é totalmente seguro.</p><p>Alguns fornecedores podem processar dados fora do Brasil. Nesses casos, buscamos utilizar fornecedores e mecanismos compatíveis com as exigências da Lei Geral de Proteção de Dados.</p></section>
      <section><h2>9. Por quanto tempo mantemos os dados</h2><p>Os dados são mantidos pelo tempo necessário para prestar o serviço e cumprir as finalidades desta Política. O prazo considera a duração da conta e dos anúncios, prevenção a fraude, segurança, obrigações legais e exercício de direitos. Depois disso, os dados podem ser excluídos, anonimizados ou conservados quando a lei permitir.</p><p>A exclusão de um anúncio o retira da visualização pública, mas cópias temporárias e registros de segurança podem permanecer por período limitado.</p></section>
      <section><h2>10. Seus direitos</h2><p>Nos casos previstos pela LGPD, você pode pedir confirmação e acesso aos dados; correção; anonimização, bloqueio ou eliminação; portabilidade quando aplicável; informação sobre compartilhamentos; revisão de decisão exclusivamente automatizada; oposição a tratamento irregular; revogação do consentimento e eliminação de dados tratados com consentimento, respeitadas as hipóteses legais de conservação.</p><p>O pedido é gratuito. Para proteger sua conta contra fraude, poderemos solicitar informações suficientes para confirmar sua identidade.</p></section>
      <section><h2>11. Como exercer seus direitos</h2><p>Envie sua solicitação para <a href="mailto:contato@acheinovale.com.br">contato@acheinovale.com.br</a>, descrevendo claramente o pedido e o e-mail ligado à conta. Responderemos conforme os requisitos e prazos aplicáveis.</p></section>
      <section><h2>12. Crianças e adolescentes</h2><p>O AcheiNoVale não é direcionado a crianças. Não publique dados de crianças ou adolescentes sem necessidade e autorização adequada. Quando houver tratamento desse tipo, serão observadas as regras legais e o melhor interesse da criança ou adolescente.</p></section>
      <section><h2>13. Incidentes de segurança</h2><p>Se identificarmos um incidente relevante envolvendo dados pessoais, adotaremos medidas de contenção, investigação e comunicação exigidas pela legislação e pelas orientações da Autoridade Nacional de Proteção de Dados.</p></section>
      <section><h2>14. Mudanças nesta Política</h2><p>Podemos atualizar esta Política por mudanças legais, novas funcionalidades, fornecedores ou práticas de segurança. A versão mais recente e a data de atualização ficarão disponíveis nesta página, e alterações relevantes poderão ser comunicadas por outros meios.</p></section>
    </LegalPage>
  );
}
